secrets:
  ngc_api_key:
    environment: NGC_CLI_API_KEY   # ホスト側で export しておく

volumes:
  a2f-3d-init-data: {}

services:
  a2f-3d-init:
    image: nvcr.io/nim/nvidia/audio2face-3d:1.3
    container_name: a2f-3d-init
    secrets: [ngc_api_key]
    working_dir: /opt/nvidia/a2f_pipeline
    entrypoint:
      - sh
      - -c
      - |
          /opt/nvidia/a2f_pipeline/service/generate_trt_models.py
    volumes:
      - a2f-3d-init-data:/tmp/a2x
      - ./configs/:/mnt/configs/
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  a2f-3d-service:
    image: nvcr.io/nim/nvidia/audio2face-3d:1.3
    secrets: [ngc_api_key]
    depends_on:
      a2f-3d-init:
        condition: service_completed_successfully
    entrypoint:
      - sh
      - -c
      - |
          a2f_pipeline.run \
            --deployment-config  /apps/configs/deployment_config.yaml \
            --stylization-config /apps/configs/stylization_config.yaml \
            --advanced-config    /apps/configs/advanced_config.yaml

    environment:
      - LD_LIBRARY_PATH=/usr/local/lib/:/root/.local/lib/
      - USE_NEW_NVSTREAMMUX=yes
      - NIM_DISABLE_MODEL_DOWNLOAD=true
      - NIM_SKIP_A2F_START=true
    volumes:
      - a2f-3d-init-data:/tmp/a2x
      - ./configs/:/mnt/configs/
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]